embedding_size: 128
feat_embed_dim: 128
# sport
#n_layers: [1]
#dropout: [0.3]
#reg_weight: [0.01, 0.001]
#teacher_weight: [0.1, 0.5, 1, 10]
#feature_weight: [0.1 , 1, 10 ,100]
#temperature: [10]
#cl_weight: 2.0

# clothing
n_layers: [1, 2]
dropout: [0.5]
reg_weight: [0.1, 0.01]
#teacher_weight: [0.05, 0.1, 0.5]
#feature_weight: [0.1 , 1, 10]
#temperature: [5, 10, 20, 50, 100]
cl_weight: 2.0


# office
#n_layers: [1, 2]
#dropout: [0.3, 0.5]
#reg_weight: [0.01, 0.001]
##teacher_weight: [0.1, 0.5, 1]
##feature_weight: [0.1 , 1, 10, 100]
##temperature: [1, 10, 50, 100]
#cl_weight: 2.0

# toysGames
#n_layers: [1]
#dropout: [0.3, 0.5]
#reg_weight: [0.1, 0.01]
##teacher_weight: [0.1, 0.5, 1]
##feature_weight: [0.1 , 1, 10, 100]
#temperature: [1, 10, 100]
#cl_weight: 2.0

# original
#n_layers: [1]
#dropout: [0.1, 0.3, 0.5]
#reg_weight: [0.1, 0.01, 0.001]
##temperature: [3]
#cl_weight: 2.0



use_neg_sampling: False

hyper_parameters: ["n_layers", "reg_weight", "dropout"]

