# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'sports.inter'

# name of features
vision_feature_file: 'FeatureImage_normal.npy'
text_feature_file: 'FeatureText_normal.npy'
meta_feature_file: 'MetaData_normal.npy'
user_graph_dict_file: 'user_graph_dict.npy'

field_separator: "\t"
